import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex h-screen w-screen overflow-x-none">
      <Sidebar />
      <div className="flex flex-col pl-24">
        <Navbar />
        <div className="w-full h-[1px] bg-[#7c7979]"></div>
        {children}
      </div>
    </div>
        </body>
    </html>
  );
}
